### ISSUE TITLE
Brave support?

### ISSUE THREAD

**Issue by kraikov** [pakokrew/mooni#45]
Hey guys, we've intergrated Mooni in our application, but for some reason it does not work on Brave. However, it works just fine on Chrome and Firefox.

![image](https://user-images.githubusercontent.com/7030722/79002362-f8d0e680-7b58-11ea-82ee-cb4aeece3a00.png)

**Comment by pakokrew** [comment]
Hey @kraikov ! 

That's a good catch, localStorage on embed websites are considered like cross-domain cookies for Brave browser. I'll try to find a solution for that. 

Thank you for pointing that

**Comment by kraikov** [comment]
Hey, do you have any ETA when Brave will be supported?

**Comment by pakokrew** [comment]
Really can't tell you as this does not depend on us.

Mooni's code does not use localStorage, but WalletConnect, Portis and 3Box do, and Bity makes use of cross-domain cookies. 

Only solution I see in the middle term would be to ask user to disable shields on your website.

**Comment by kraikov** [comment]
There is now warning inside the iframe when using Brave. That's helpful. Thanks.

**Comment by pakokrew** [comment]
Mooni is now working well with brave.
