### ISSUE TITLE
Validation on the reference field fails when writing a comma

### ISSUE THREAD

**Issue by The-3D** [pakokrew/mooni#69]
The reference for the bank transfer i need to write includes a comma, and the validation on the reference field fails and the app crashes. Console shows the following:
![image](https://user-images.githubusercontent.com/37953689/85408214-858a1e80-b564-11ea-9212-322d817656cb.png)

can be reproduced in both coinbase wallet mobile and firefox desktop

**Comment by pakokrew** [comment]
Fixed
